IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200

DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
DEFAULT_SYSTEM_PROMPT = "You are a helpful assistant."

SUPPORTED_TRANSFORMERS_MIN = "4.39.2"
SUPPORTED_TRANSFORMERS_MAX = "4.45.1"
SUPPORTED_TRANSFORMERS_RANGE = (
    f">={SUPPORTED_TRANSFORMERS_MIN},<={SUPPORTED_TRANSFORMERS_MAX}"
)
